INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Maru Box', 'odd', 300.00, 'August','December');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Flipdip', 'cool', 3.50, 'This day','That day');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Maru Box','fun', 300.00, 'August','December');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Maru Box', 'lame', 300.00, 'August','December');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Maru Box', 'fun', 300.00, 'August','December');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Maru Box', 'lame', 300.00, 'August','December');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Maru Box', 'odd', 300.00, 'August','December');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Maru Box', 'cool', 300.00, 'August','December');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Maru Box', 'fun', 300.00, 'August','December');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Maru Box', 'lame', 300.00, 'August','December');

INSERT INTO users (name, age) VALUES ('Maru ', 81);
INSERT INTO users (name, age) VALUES ('bill ', 8);
INSERT INTO users (name, age) VALUES ('ed ', 8);
INSERT INTO users (name, age) VALUES ('tom ', 18);
INSERT INTO users (name, age) VALUES ('billy ', 8);
INSERT INTO users (name, age) VALUES ('markl ', 8);
INSERT INTO users (name, age) VALUES ('framl ', 6);
INSERT INTO users (name, age) VALUES ('gerbn ', 2);
INSERT INTO users (name, age) VALUES ('ferb ', 1);
INSERT INTO users (name, age) VALUES ('myi ', 354);
INSERT INTO users (name, age) VALUES ('asd ', 63);
INSERT INTO users (name, age) VALUES ('rtuy ', 8);
INSERT INTO users (name, age) VALUES ('cvn ', 6);
INSERT INTO users (name, age) VALUES ('er ', 8);
INSERT INTO users (name, age) VALUES ('gah ', 3);
INSERT INTO users (name, age) VALUES ('gtr ', 21);
INSERT INTO users (name, age) VALUES ('uip ', 12);
INSERT INTO users (name, age) VALUES ('tyu ', 24);
INSERT INTO users (name, age) VALUES ('fP ', 4);
INSERT INTO users (name, age) VALUES ('tipo ', 18);

INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 3, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 3, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 5, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2060, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2060, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2400, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 30);